version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      wasmtime-crates:
        patterns:
          - wasmtime-wasi
          - wasi-common
          - wasmtime

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
